version: '3.4'

services:
  testbackend.fundtransfer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "RedisCacheSettingsConnectionString=localhost:6379"
      - "RabbitEventBusSettings:HostAddress=amqp://guest:guest@localhost:5672"
      - "MongoDatabaseSettings:ConnectionString=mongodb://localhost:27017"
      - "MongoDatabaseSettings:DatabaseName=FundTransferDb"
      - "MongoDatabaseSettings:CollectionName=FundTransfers"
      - "AcessoEndpointSettings:BaseUrl=http://localhost:5000"
    ports:
      - "8001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  testbackend.fundtransfer.api.consumer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "RedisCacheSettingsConnectionString=localhost:6379"
      - "RabbitEventBusSettings:HostAddress=amqp://guest:guest@localhost:5672"
      - "MongoDatabaseSettings:ConnectionString=mongodb://localhost:27017"
      - "MongoDatabaseSettings:DatabaseName=FundTransferDb"
      - "MongoDatabaseSettings:CollectionName=FundTransfers"
      - "AcessoEndpointSettings:BaseUrl=http://localhost:5000"
    ports:
      - "8002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
